import { describe, expect, it } from 'vitest'
import { parser } from 'sax'
import editorDocument from './fixtures/survey-design/editor-vector-document.json'
import { SurveyDesignExportError, surveyDesignSvg } from './survey-design-export.js'

// Generated by createDesignDocument / createDesignElement / createDesignPage,
// then checked with validateDesignDocumentStructure in src/shared/design-document.ts.
type FixtureElement = {
  id: string; type: string; x: number; y: number; w: number; h: number
  rotation: number; zIndex: number; fill?: string; text?: string
  fontFamily?: string; pathData?: string; childIds?: string[]; hidden?: boolean
  [key: string]: unknown
}
type FixtureDocument = {
  schemaVersion: string
  pages: Array<{ id: string; name: string; width: number; height: number; displayMode?: string; elements: FixtureElement[] }>
  assets: unknown[]
}
function document(): FixtureDocument { return structuredClone(editorDocument) }
function nodes(svg: string) {
  const result: Array<{ name: string; attrs: Record<string, string> }> = []
  const xml = parser(true)
  xml.onopentag = (node) => { result.push({ name: node.name, attrs: node.attributes as Record<string, string> }) }
  xml.write(svg).close()
  return result
}

describe('Survey editable Design vector export', () => {
  it('exports the real editor shapes, signed lines, styles, preset geometry and text', () => {
    const svg = surveyDesignSvg(document(), { coordinateSystem: '工程独立坐标系', units: 'm' })
    const elements = nodes(svg)
    expect(elements.some(n => n.name === 'ellipse' && n.attrs.cx === '185')).toBe(true)
    expect(elements.some(n => n.name === 'line' && n.attrs.x2 === '200' && n.attrs.y2 === '200')).toBe(true)
    expect(elements.some(n => n.name === 'rect' && n.attrs.transform === 'rotate(15 390 270)')).toBe(true)
    expect(elements.some(n => n.name === 'path' && n.attrs.opacity === '0.6')).toBe(true)
    expect(elements.some(n => n.name === 'path' && n.attrs.fill === 'none' && n.attrs.stroke === '#FFFFFF')).toBe(true)
    expect(elements.some(n => n.name === 'g' && n.attrs.transform === 'translate(600 450) scale(0.5 0.5)')).toBe(true)
    expect(elements.some(n => n.name === 'text' && n.attrs['text-anchor'] === 'middle' && n.attrs['letter-spacing'] === '1')).toBe(true)
    expect(elements.filter(n => n.name === 'tspan')).toHaveLength(2)
    expect(svg).toContain('工程独立坐标系')
    expect(svg).toContain('单位：m')
    expect(svg).toContain('待审草稿')
    expect(svg).toContain('非比例示意')
    expect(svg).not.toMatch(/href=|<script|foreignObject|\son\w+=/i)
  })

  it('exports every page with its original dimensions and nonoverlapping layout', () => {
    const elements = nodes(surveyDesignSvg(document()))
    const pages = elements.filter(n => n.name === 'svg').slice(1)
    expect(pages).toHaveLength(2)
    expect(pages[0]!.attrs.viewBox).toBe('0 0 800 600')
    expect(pages[1]!.attrs.viewBox).toBe('0 0 600 300')
    expect(Number(pages[1]!.attrs.y)).toBeGreaterThan(Number(pages[0]!.attrs.y) + 600)
    expect(elements[0]!.attrs.width).toBe('800')
  })

  it('does not apply group rotation twice or alter global layer order', () => {
    const svg = surveyDesignSvg(document())
    expect(svg).not.toContain('rotate(30')
    expect(svg.indexOf('<ellipse')).toBeLessThan(svg.indexOf('<line'))
    expect(svg.match(/<ellipse/g)).toHaveLength(1)
  })

  it('escapes text and font metadata without treating them as markup', () => {
    const raw = document()
    raw.pages[1]!.elements[0]!.text = 'A & B <script>alert(1)</script>'
    raw.pages[1]!.elements[0]!.fontFamily = 'A" onload="bad'
    const svg = surveyDesignSvg(raw)
    nodes(svg)
    expect(svg).toContain('A &amp; B &lt;script&gt;alert(1)&lt;/script&gt;')
    expect(svg).not.toContain('<script>')
    expect(svg).toContain('font-family="A&quot; onload=&quot;bad"')
  })

  it.each([
    'M0,0 L20', 'M0 0 A10 10 0 2 0 30 40', 'M0 0 L1e999 10',
    'M0 0 L1 2"><script/>', 'url(https://example.com/a)', 'L0 0',
    'M0,,0', 'M0 0 Z 20 30', 'M0 0 A-10 10 0 0 0 10 10'
  ])('blocks malformed or active path data: %s', pathData => {
    const raw = document()
    raw.pages[0]!.elements[3]!.pathData = pathData
    expect(() => surveyDesignSvg(raw)).toThrow(SurveyDesignExportError)
  })

  it.each([
    'M0 0 C1 2 3 4 5 6 S7 8 9 10 Q11 12 13 14 T15 16 Z',
    'M1e-2,0.5 h10 v-10 a5 5 0 0 1 2 3 z',
    'M0 0 10 10 20 20 L30 30', 'M.1-.2L.3.4',
    'M0 0 A10 20 45 0 1 30 40'
  ])('accepts valid editor path geometry: %s', pathData => {
    const raw = document()
    raw.pages[0]!.elements[3]!.pathData = pathData
    expect(() => nodes(surveyDesignSvg(raw))).not.toThrow()
  })

  it.each(['image', 'fidelity', 'asset', 'preset-without-geometry'])('blocks unsupported content instead of silently losing it: %s', kind => {
    const raw = document() as any
    if (kind === 'image') raw.pages[1].elements[0].type = 'image'
    if (kind === 'fidelity') raw.pages[1].displayMode = 'fidelity'
    if (kind === 'asset') raw.assets = [{ id: 'asset_1', filename: 'field.png', mimeType: 'image/png', width: 1, height: 1, byteSize: 1 }]
    if (kind === 'preset-without-geometry') delete raw.pages[0].elements[6].presetPaths
    expect(() => surveyDesignSvg(raw)).toThrow(SurveyDesignExportError)
  })

  it.each(['duplicate', 'missing-child', 'cycle', 'two-parents'])('blocks damaged group references: %s', kind => {
    const raw = document()
    const group = raw.pages[0]!.elements[5]!
    if (kind === 'duplicate') raw.pages[0]!.elements[1]!.id = raw.pages[0]!.elements[0]!.id
    if (kind === 'missing-child') group.childIds = ['missing']
    if (kind === 'cycle') group.childIds = [group.id]
    if (kind === 'two-parents') raw.pages[0]!.elements.push({ ...group, id: 'el_group2' })
    expect(() => surveyDesignSvg(raw)).toThrow(SurveyDesignExportError)
  })

  it('omits explicitly hidden vectors and rejects unbounded geometry and external paint', () => {
    const hidden = document()
    hidden.pages[0]!.elements[1]!.hidden = true
    expect(surveyDesignSvg(hidden)).not.toContain('<ellipse')
    const invalid = document()
    invalid.pages[0]!.elements[0]!.x = Infinity
    expect(() => surveyDesignSvg(invalid)).toThrow(SurveyDesignExportError)
    invalid.pages[0]!.elements[0]!.x = 20
    invalid.pages[0]!.elements[0]!.fill = 'url(https://example.com/paint)'
    expect(() => surveyDesignSvg(invalid)).toThrow(SurveyDesignExportError)
  })
})
